### ISSUE TITLE
Unable to sign up as an event organizer

### ISSUE THREAD

**Issue by Tonkpils** [kaykayyali/plannify.us#1]
## Steps to reproduce
- filled out information
- clicked sign up button
## Expected Outcome

A new account to be created with my email and information
## Actual Outcome

No feedback was given and no account was created
Also received this in the console
![image](https://cloud.githubusercontent.com/assets/1507561/8946038/e05985a6-355a-11e5-8222-53903f1fc35e.png)

**Comment by kaykayyali** [comment]
This is a weird one. Usually fixed by simply refreshing the page. Javascript is bugging

**Comment by Tonkpils** [comment]
Seems the javascript that's making the AJAX request is failing

**Comment by kaykayyali** [comment]
Yeah,  I might redo it, but it's the basic devise signup for helper.

**Comment by kaykayyali** [comment]
Im going to redo this page next week after basic functionality is finished.

**Comment by kaykayyali** [comment]
This was corrected. Vendor Javascript was interfering somehow.
