### ISSUE TITLE
As an event organizer, I should be able to...

### ISSUE THREAD

**Issue by Tonkpils** [kaykayyali/plannify.us#2]
## Use Cases
- [x] Post new events 
- [x] List vendors with a profile
- [x] Find service providers for their event
- [x] Have an open conversation with service providers through a chat box on the event page
- [x] View Service providers who have offered to provide a service
- [x] Confirm a service provider for their event

**Comment by kaykayyali** [comment]
## Use Cases
-[x] Post new events 
-[] Find service providers for their event
-[] View Service providers who have offered to provide a service
-[] Confirm a service provider for their event
-[] Have an open conversation with service providers through a chat box on the event page

**Comment by kaykayyali** [comment]
Note to self, set up way for vendors to directly message organizer
